# Generated by Django 5.0.4 on 2024-05-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cac_onboarding_backend", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("streetname", models.CharField(max_length=150)),
                ("durationtime", models.IntegerField()),
                ("importance", models.IntegerField()),
            ],
        ),
    ]
