# Generated by Django 5.0.4 on 2024-05-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cac_onboarding_backend", "0002_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location_Map",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("duration", models.IntegerField()),
                ("cost", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
